### PR TITLE
make create-clusters.sh work based on kind document

### LINKED ISSUE #1322: create cluster script does not work by default according to kind document
**What happened**:
```
$ ./scripts/create-clusters.sh 
Creating 2 clusters
ERROR: unknown command "" for "kind create cluster"
```

/kind bug

### PR DESCRIPTION
**Pull request by xunpan**
**What this PR does / why we need it**:
The script should work based on documents.
1. I add default TAG for the node image to make it work by default.
2. I add 2 environment variables documented in kind doc

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1322

**Special notes for your reviewer**:

### CODE REVIEW

File: scripts/create-clusters.sh [hunk 1]
```diff
@@ -25,7 +25,7 @@ set -o pipefail
 source "${BASH_SOURCE%/*}/util.sh"
 NUM_CLUSTERS="${NUM_CLUSTERS:-2}"
 KIND_IMAGE="${KIND_IMAGE:-}"
-KIND_TAG="${KIND_TAG:-}"
+KIND_TAG="${KIND_TAG:-v1.18.4}"
```
Comment (makkes) [inline scripts/create-clusters.sh:28]: In the [pre-commit hook](https://github.com/kubernetes-sigs/kubefed/blob/ecd49000b586e2ed29e3a1b938e2f85772358843/scripts/pre-commit.sh#L139) we're using `v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600`. I'd recommend to use the same version by default or rather pull the version in from there or some other common location so we don't have to maintain two locations for this variable.

Comment (xunpan) [reply scripts/create-clusters.sh]: That makes sense. I referred an old version before 1.19.1. It is updated. Thanks @makkes

File: tools/go.mod [hunk 2]
```diff
@@ -4,5 +4,7 @@ go 1.13
 
 require (
 	github.com/go-bindata/go-bindata/v3 v3.1.3
+	github.com/gobuffalo/flect v0.2.2 // indirect
+	gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776 // indirect
```
Comment (makkes) [inline tools/go.mod:8]: I'm not sure how these two ended up in here but I'd recommend removing these lines. @jimmidyson you have a hunch what might have caused these to be added?

File: tools/go.sum [hunk 3]
```diff
@@ -123,6 +123,8 @@ github.com/go-openapi/validate v0.19.5/go.mod h1:8DJv2CVJQ6kGNpFW6eV9N3JviE1C85n
 github.com/go-stack/stack v1.8.0/go.mod h1:v0f6uXyyMGvRgIKkXu+yp6POWl0qKG85gN/melR3HDY=
 github.com/gobuffalo/flect v0.2.0 h1:EWCvMGGxOjsgwlWaP+f4+Hh6yrrte7JeFL2S6b+0hdM=
 github.com/gobuffalo/flect v0.2.0/go.mod h1:W3K3X9ksuZfir8f/LrfVtWmCDQFfayuylOJ7sz/Fj80=
+github.com/gobuffalo/flect v0.2.2 h1:PAVD7sp0KOdfswjAw9BpLCU9hXo7wFSzgpQ+zNeks/A=
+github.com/gobuffalo/flect v0.2.2/go.mod h1:vmkQwuZYhN5Pc4ljYQZzP+1sq+NEkK+lh20jmEmX3jc=
```
Comment (makkes) [inline tools/go.sum:127]: see my comment on `go.mod`.

File: tools/go.sum [hunk 4]
```diff
@@ -430,6 +432,8 @@ gopkg.in/yaml.v2 v2.2.8 h1:obN1ZagJSUGI0Ek/LBmuj4SNLPfIny3KsKFopxRdj10=
 gopkg.in/yaml.v2 v2.2.8/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
 gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966 h1:B0J02caTR6tpSJozBJyiAzT6CtBzjclw4pgm9gg8Ys0=
 gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
+gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776 h1:tQIYjPdBoyREyB9XMu+nnTclpTYkz2zFM+lzLJFO4gQ=
+gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
```
Comment (makkes) [inline tools/go.sum:436]: see my comment on `go.mod`.

**Review by makkes — COMMENTED** [review]
just a nit, otherwise lgtm.

File: tools/go.mod (hunk 2 above)
Comment (xunpan) [reply tools/go.mod]: agreed to remove it from the PR because it is an independent issue.

File: docs/environments/kind.md [hunk 5]
```diff
@@ -43,6 +43,19 @@ script if you'd like to change the default:
 NUM_CLUSTERS=<num> ./scripts/create-clusters.sh
 ```
 
+The `KIND_TAG` is `v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600` by default.
+Image `kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600` is used as
+node docker image for booting the cluster.
+
+You can use `KIND_IMAGE` or `KIND_TAG` to specify the image as you want.
+```bash
+KIND_TAG=v1.18 ./scripts/create-clusters.sh
```
Comment (jimmidyson) [inline docs/environments/kind.md:52]: I know this is an example but `v1.18` isn't a valid tag (people like to copy-paste). Let's use something like:
```suggestion
KIND_TAG=v1.18.8 ./scripts/create-clusters.sh
```

File: docs/environments/kind.md [hunk 6]
```diff
@@ -43,6 +43,19 @@ script if you'd like to change the default:
...
+```
+
+```bash
+KIND_IMAGE=kindest/node:v1.18 ./scripts/create-clusters.sh
```
Comment (jimmidyson) [inline docs/environments/kind.md:56]:
```suggestion
KIND_IMAGE=kindest/node:v1.18.8 ./scripts/create-clusters.sh
```

File: scripts/create-clusters.sh [hunk 7]
```diff
@@ -25,7 +25,7 @@ set -o pipefail
 source "${BASH_SOURCE%/*}/util.sh"
 NUM_CLUSTERS="${NUM_CLUSTERS:-2}"
 KIND_IMAGE="${KIND_IMAGE:-}"
-KIND_TAG="${KIND_TAG:-}"
+KIND_TAG="${KIND_TAG:-v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600}"
```
Comment (jimmidyson) [inline scripts/create-clusters.sh:28]: Let's take advantage and bump to latest:
```suggestion
KIND_TAG="${KIND_TAG:-v1.19.4@sha256:796d09e217d93bed01ecf8502633e48fd806fe42f9d02fdd468b81cd4e3bd40b}"
```

Will need to update https://github.com/kubernetes-sigs/kubefed/blob/ecd49000b586e2ed29e3a1b938e2f85772358843/scripts/pre-commit.sh#L139 too.

**Review by jimmidyson — CHANGES_REQUESTED** [review]
Can we please update the example to use a real tag, and I'd really like it if we could take this opportunity to upgrade to latest kind images.

**Comment by xunpan** [comment]
I use 1 commit because updating tag version is simple and easy to understand.

**Review by jimmidyson — APPROVED** [review]
