### PR TITLE
Set kubefed-namespace via the config mechanism for in-cluster deployment

### LINKED ISSUE #795: use namespace from system in
**What happened**:

**What you expected to happen**:
It would be desirable to set federation-namespace via the config mechanism if scope == Namespace.

Follow up action for https://github.com/kubernetes-sigs/federation-v2/pull/771

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version
- Install method (helm vs script)
- Install configuration (namespaced vs cluster-scoped)
- Others

/kind bug

### PR DESCRIPTION
**Pull request by sohankunkerkar**
Fixes #795 
/assign @marun @xunpan

### CODE REVIEW

File: cmd/controller-manager/app/controller-manager.go [hunk 1]
```diff
@@ -117,6 +117,17 @@ func Run(opts *options.Options) error {
 		klog.Fatalf("Invalid Feature Gate: %v", err)
 	}
 
+	// for in-cluster deployment set the namespace associated
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: Discovery of the kubefed namespace should only be attempted if it was not supplied explicitly and the configuration indicates that the controller manager is running inside a cluster i.e. the following conditions:

 - `len(opts.Config.FederationNamespace) == 0`
 - `len(masterURL) == 0`
 - `len(kubeconfig) == 0`

File: cmd/controller-manager/app/controller-manager.go [hunk 2]
```diff
@@ -117,6 +117,17 @@ func Run(opts *options.Options) error {
...
+	// with the service account token
+	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: We already have a valid config at this point, and the logic for discovering the namespace of the service account doesn't depend on the config at all.  It's just [5 lines of go code](https://github.com/kubernetes-sigs/federation-v2/blob/master/vendor/k8s.io/client-go/tools/clientcmd/client_config.go#L521).  I'd suggest creating a local function with this code or just adding it inline:

```golang
// Fall back to the namespace associated with the service account token, if available
if data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace"); err == nil {
  if ns := strings.TrimSpace(string(data)); len(ns) > 0 {
    return ns, false, nil
  }
}
```

If the federation namespace is not specified and cannot be discovered via this method, the controller manager should log a fatal error indicating that the federation namespace needs to be manually set via `--federation-config` if the controller manager is not running inside a cluster.

File: cmd/controller-manager/app/controller-manager.go (hunk 1 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Thanks, @marun. I will update this PR to check for this condition before setting up the value for the `federation namespace`.

File: cmd/controller-manager/app/controller-manager.go (hunk 2 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Ack. I will make the necessary changes in the code as per your suggestions.

File: cmd/controller-manager/app/controller-manager.go [hunk 3]
```diff
@@ -95,6 +97,17 @@ member clusters and does the necessary reconciliation`,
 	return cmd
 }
 
+// for in-cluster deployment set the namespace associated
+// with the service account token
+func defaultNamespace() (string, error) {
+	if data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace"); err == nil {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: `err` needs to be checked and returned if non-nil.

File: cmd/controller-manager/app/controller-manager.go [hunk 4]
```diff
@@ -117,6 +130,14 @@ func Run(opts *options.Options) error {
 		klog.Fatalf("Invalid Feature Gate: %v", err)
 	}
 
+	if len(masterURL) == 0 && len(kubeconfig) == 0 && len(opts.Config.FederationNamespace) == 0 {
+		fedName, err := defaultNamespace()
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: `s/fedName/fedNamespace/`

Please use clear and unambiguous names.  Avoid brief names that are insufficiently descriptive.

File: cmd/controller-manager/app/controller-manager.go [hunk 5]
```diff
@@ -117,6 +130,14 @@ func Run(opts *options.Options) error {
...
+		if err != nil {
+			klog.Fatalf("The controller-manager is not running inside the cluster. Use --federation-namespace flag to manually set the fedeation-namespace")
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: The error should be logged and the namespace flag should be checked outside of this conditional, i.e.

```golang
if len(masterURL)... {
  fedNamespace, err := ...
  if err != nil {
    // Include the err in the log message to aid in troubleshooting
    klog.Fatalf("An error occurred while attempting to discover the federation namespace from the service account: %v", err)
  } 
}

// Regardless of whether in-cluster discovery was attempted, validate that a federation namespace is configured 
if len(opts.Config.FederationNamespace) == 0 {
  klog.Fatalf("The federation namespace must be specified via --federation-namespace")
} 
```

Errors should almost always be logged unless you have a good reason not to.  It's entirely possible the error will convey information vital to a troubleshooting exercise.

Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: ack

File: cmd/controller-manager/app/controller-manager.go [hunk 6]
```diff
@@ -56,7 +58,7 @@ import (
 )
 
 var (
-	kubeconfig, federationConfig, masterURL string
+	kubeconfig, federationConfig, masterURL, fedNamespace string
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: Variable definitions should have the minimal scope required. This variable is package global, but is only used within the scope of a conditional in a function.  As per subsequent comments, though, this variable is not  necessary and can be removed.

File: cmd/controller-manager/app/controller-manager.go [hunk 7]
```diff
@@ -117,6 +119,25 @@ func Run(opts *options.Options) error {
 		klog.Fatalf("Invalid Feature Gate: %v", err)
 	}
 
+	// validate if a federation namespace is configured
+	if len(opts.Config.FederationNamespace) == 0 {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: This block needs to appear after the block that tries to discover the namespace to ensure that discovery can be attempted if the namespace is not otherwise provided.

File: cmd/controller-manager/app/controller-manager.go [hunk 8]
```diff
@@ -117,6 +119,25 @@ func Run(opts *options.Options) error {
...
+		klog.Fatalf("The federation namespace must be specified via --federation-namespace")
+	}
+
+	if len(masterURL) == 0 && len(kubeconfig) == 0 && len(opts.Config.FederationNamespace) == 0 {
+		// for in-cluster deployment set the namespace associated
+		// with the service account token
+		data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
+		if err != nil {
+			klog.Fatalf("An error occurred while attempting to discover the federation namespace from the service account: %v", err)
+		} else {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: This else block is unnecessary since `klog.Fatalf` will exit the process.

File: cmd/controller-manager/app/controller-manager.go [hunk 9]
```diff
@@ -117,6 +119,25 @@ func Run(opts *options.Options) error {
...
+			if ns := strings.TrimSpace(string(data)); len(ns) > 0 {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: There is no need for this conditional or intermediate variable.  The following will suffice:

```golang
opts.Config.FederationNamespace = strings.TrimSpace(string(data))
```

An empty string value is fine.  It won't change anything because a condition of this block is that the federation namespace is not set.

File: cmd/controller-manager/app/controller-manager.go [hunk 10]
```diff
@@ -117,6 +119,25 @@ func Run(opts *options.Options) error {
 		klog.Fatalf("Invalid Feature Gate: %v", err)
 	}
 
+	// validate if a federation namespace is configured
+	if len(opts.Config.FederationNamespace) == 0 {
+		klog.Fatalf("The federation namespace must be specified via --federation-namespace")
+	}
+
+	if len(masterURL) == 0 && len(kubeconfig) == 0 && len(opts.Config.FederationNamespace) == 0 {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: (No action required) It's often helpful to use a boolean variable to document your intent with a conditional, e.g.

```golang
runningInCluster := len(masterURL) == 0 && len(kubeconfig) == 0
if runningInCluster && len(opts.Config.FederationNamespace) == 0 {
 ...
}
```

File: cmd/controller-manager/app/controller-manager.go (hunk 6 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Yeah, I think that makes sense. I will update this PR accordingly.

File: cmd/controller-manager/app/controller-manager.go (hunk 8 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Done!

File: cmd/controller-manager/app/controller-manager.go (hunk 9 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Yeah, I was concerned about the empty string here but as you mentioned it won't affect the overall process for setting the federation namespace.

File: cmd/controller-manager/app/controller-manager.go (hunk 10 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: I think I like your rationale for clubbing two conditions here and mentioning the exact intent behind it. I will accommodate this change in this PR.

File: cmd/controller-manager/app/controller-manager.go (hunk 7 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Fixed.

**Comment by marun** [comment]
LGTM

**Comment by sohankunkerkar** [comment]
@marun ready for your review.

File: cmd/controller-manager/app/controller-manager.go [hunk 11]
```diff
@@ -107,12 +109,28 @@ func Run(opts *options.Options, stopChan <-chan struct{}) error {
...
+		data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
+		if err != nil {
+			klog.Fatalf("An error occurred while attempting to discover the kubefed namespace from the service account: %v", err)
+		}
+		opts.Config.KubeFedNamespace = strings.TrimSpace(string(data))
+	}
+
+	setOptionsByKubeFedConfig(opts)
+
+	// validate if a kubefed namespace is configured
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: Please follow the convention of capitalizing the first word in a comment e.g. `Validate if a kubefed namespace is configured`

File: cmd/controller-manager/app/controller-manager.go [hunk 12]
```diff
@@ -107,12 +109,28 @@ func Run(opts *options.Options, stopChan <-chan struct{}) error {
...
+	if len(opts.Config.KubeFedNamespace) == 0 {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: This check needs to occur before `setOptionsByKubeFedConfig` is called to ensure that the check's error message will appear in the logs instead of a complaint that a namespace must be set from an attempt to load a KubeFedConfig resource.

File: cmd/controller-manager/app/controller-manager.go [hunk 13]
```diff
@@ -107,12 +109,28 @@ func Run(opts *options.Options, stopChan <-chan struct{}) error {
 		panic(err)
 	}
 
-	setOptionsByKubeFedConfig(opts)
-
 	if err := utilfeature.DefaultFeatureGate.SetFromMap(opts.FeatureGates); err != nil {
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: This check needs to occur after `setOptionsByKubeFedConfig` is called because it depends on `opts.FeatureGates` being set by the call.

File: cmd/controller-manager/app/controller-manager.go (hunk 11 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Fixed

File: cmd/controller-manager/app/controller-manager.go (hunk 12 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Fixed

File: cmd/controller-manager/app/controller-manager.go (hunk 13 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Ack

**Comment by sohankunkerkar** [comment]
@marun your comments have been addressed. PTAL

File: charts/kubefed/charts/controllermanager/templates/deployments.yaml [hunk 14]
```diff
@@ -20,9 +20,7 @@ spec:
         runAsUser: 1001
       serviceAccountName: kubefed-controller
       containers:
-      - args:
-        - --kubefed-namespace=$(KUBEFED_NAMESPACE)
```
Comment (marun) [inline charts/kubefed/charts/controllermanager/templates/deployments.yaml]: Please remove the now-unused env entry for KUBEFED_NAMESPACE (L39-L43).

Comment (sohankunkerkar) [reply charts/kubefed/charts/controllermanager/templates/deployments.yaml]: Fixed

**Comment by sohankunkerkar** [comment]
@marun PTAL :)

File: pkg/controller/util/cluster_util.go [hunk 15]
```diff
@@ -32,10 +32,9 @@ import (
 
 const (
 	DefaultKubeFedSystemNamespace = "kube-federation-system"
-
-	KubeAPIQPS   = 20.0
-	KubeAPIBurst = 30
-	TokenKey     = "token"
+	KubeAPIQPS                    = 20.0
+	KubeAPIBurst                  = 30
+	TokenKey                      = "token"
```
Comment (marun) [inline pkg/controller/util/cluster_util.go]: Please revert this unrelated change.

File: cmd/controller-manager/app/controller-manager.go [hunk 16]
```diff
@@ -107,6 +109,22 @@ func Run(opts *options.Options, stopChan <-chan struct{}) error {
...
+		data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
+		if err != nil {
+			klog.Fatalf("An error occurred while attempting to discover the kubefed namespace from the service account: %v", err)
+		}
+		opts.Config.KubeFedNamespace = strings.TrimSpace(string(data))
+	}
+
+	// Validate if a kubefed-namespace is configured
+	if len(opts.Config.KubeFedNamespace) == 0 {
+		klog.Fatalf("The kubefed namespace must be specified via --kubefed-namespace")
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: nit: Please prefer KubeFed in output seen by the user.

File: cmd/controller-manager/app/controller-manager.go [hunk 17]
```diff
@@ -107,6 +109,22 @@ func Run(opts *options.Options, stopChan <-chan struct{}) error {
 		panic(err)
 	}
 
+	runningInCluster := len(masterURL) == 0 && len(kubeconfig) == 0
+	if runningInCluster && len(opts.Config.KubeFedNamespace) == 0 {
+		// For in-cluster deployment set the namespace associated
+		// with the service account token
+		data, err := ioutil.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
+		if err != nil {
+			klog.Fatalf("An error occurred while attempting to discover the kubefed namespace from the service account: %v", err)
```
Comment (marun) [inline cmd/controller-manager/app/controller-manager.go]: nit: Please prefer KubeFed in output seen by the user.

File: charts/kubefed/charts/controllermanager/templates/deployments.yaml [hunk 18]
```diff
@@ -38,11 +36,6 @@ spec:
 {{- if .Values.resources }}
 {{ toYaml .Values.resources | indent 12 }}
 {{- end }}
-        env:
```
Comment (marun) [inline charts/kubefed/charts/controllermanager/templates/deployments.yaml]: 👍

**Comment by marun** [comment]
A few more nits, sorry for not catching earlier!

File: pkg/controller/util/cluster_util.go (hunk 15 above)
Comment (sohankunkerkar) [reply pkg/controller/util/cluster_util.go]: This is related to the `go-fmt` issue. Let me paste the code as-is.

File: cmd/controller-manager/app/controller-manager.go (hunk 16 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Done.

File: cmd/controller-manager/app/controller-manager.go (hunk 17 above)
Comment (sohankunkerkar) [reply cmd/controller-manager/app/controller-manager.go]: Done

**Comment by sohankunkerkar** [comment]
@marun All the comments have been addressed.

**Comment by marun** [comment]
Thank you!

/approve
