### PR TITLE
Require the spec field in generated federated types

### LINKED ISSUE #1079: Missing spec field causes Controller CrashLoopBackOff
**What happened**:
FederatedSecrets / FederatedConfigmaps takes up to 30 minutes to be visible in
joined clusters. After several minutes some of them are visible,.....after minutes next
ConfigMaps comes (maybe)
You can't rely on the Secrects or ConfigMaps being synchronized at all. Some are not sync

**What you expected to happen**:
new created Federated#### comes within minutes and not hours

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- KubeFed version
``` 
kubefedctl version: version.Info{Version:"v0.1.0-rc5-dirty", GitCommit:"99be0218bf5ac7d560ec0d7c2cfbfcbb86ba2d61", GitTreeState:"dirty", BuildDate:"2019-08-01T15:41:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}

``` 
- Scope of installation (namespaced or cluster)
cluster

- Others

/kind bug

### PR DESCRIPTION
**Pull request by marun**
A missing spec field in a federated resource is a potential indication of a malformed resource. For existing resources, a check has been added for a missing spec field before attempting to compute a hash of overrides to prevent a nil pointer exception.

Fixes #1079

### CODE REVIEW

File: test/e2e/framework/framework.go [hunk 1]
```diff
@@ -259,13 +259,13 @@ func (f *frameworkWrapper) EnsureTestFederatedNamespace(allClusters bool) *unstr
...
 	if allClusters {
 		// An empty cluster selector field selects all clusters
-		obj.Object[util.SpecField] = map[string]interface{}{
-			util.PlacementField: map[string]interface{}{
-				util.ClusterSelectorField: map[string]interface{}{},
-			},
+		obj.Object[util.SpecField][util.PlacementField] = map[string]interface{}{
+			util.ClusterSelectorField: map[string]interface{}{},
 		}
+	} else {
```
Comment (font) [inline test/e2e/framework/framework.go]: ?

File: pkg/kubefedctl/enable/validation.go [hunk 2]
```diff
@@ -243,6 +243,14 @@ func ValidationSchema(specProps v1beta1.JSONSchemaProps) *v1beta1.CustomResource
 					},
 				},
 			},
+			// Require a spec (even if empty) as an aid to users
+			// manually creating federated configmaps or
+			// secrets. These target types do not include a spec,
+			// and the absence of the spec in a federated
+			// equivalent could indicate a malformed resource.
```
Comment (font) [inline pkg/kubefedctl/enable/validation.go]: Wouldn't the lack of `spec` in a federated equivalent always indicate a malformed resource? Otherwise there'd be no way to provide overrides, placement, etc.

File: test/e2e/framework/framework.go (hunk 1 above)
Comment (marun) [reply test/e2e/framework/framework.go]: Done.

File: pkg/kubefedctl/enable/validation.go (hunk 2 above)
Comment (marun) [reply pkg/kubefedctl/enable/validation.go]: Not necessarily - overrides are entirely optional, the absence of placement indicates that the resource should not exist in any cluster, and namespaces don't even require a template.

**Comment by marun** [comment]
Fixed lint error.

**Comment by xunpan** [comment]
/lgtm
I think it is ready to merge.
