### PR TITLE
Make KubeFedConfig scope immutable

### LINKED ISSUE #1058: KubeFedConfig scope should be immutable
**What happened**:
Modifying the `kubefed` KubeFedConfig `scope` from `Cluster` to `Namespaced` succeeded.

**What you expected to happen**:
Validation failure suggesting the field is immutable.

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy cluster-scoped kubefed
2. modify the scope in the `kubefed` KubeFedConfig to `Namespaced`

**Anything else we need to know?**:
See #916 for more details.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.2
- KubeFed version: v0.1.0-rc4
- Scope of installation (namespaced or cluster): cluster
- Others

/kind bug

### PR DESCRIPTION
**Pull request by font**
**What this PR does / why we need it**:
This PR makes the KubeFedConfig `spec.scope` field immutable.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1058 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by xunpan** [comment]
LGTM

**Comment by shashidharatd** [comment]
LGTM

File: pkg/apis/core/v1beta1/validation/validation.go [hunk 1]
```diff
@@ -254,14 +254,18 @@ func validateClusterCondition(cc *v1beta1.ClusterCondition, path *field.Path) fi
 	return allErrs
 }
 
-func ValidateKubeFedConfig(kubeFedConfig *v1beta1.KubeFedConfig) field.ErrorList {
+func ValidateKubeFedConfig(kubeFedConfig, oldKubeFedConfig *v1beta1.KubeFedConfig, update bool) field.ErrorList {
```
Comment (marun) [inline pkg/apis/core/v1beta1/validation/validation.go]: Could `update` be computed as `oldKubeFedConfig != nil`?
