### PR TITLE
idempotent unjoin

### LINKED ISSUE #745: Unjoin should be idempotent
Currently, attempting to unjoin an already-unjoined cluster will result in error messages as unjoin tries and fails to remove resources that do not exist in the cluster targeted for unjoin.  Similar to join, unjoin should default to not reporting errors of missing resources unless provided with an argument like `--error-on-missing`.

/king bug

### PR DESCRIPTION
**Pull request by xunpan**
`unjoin`: when resources does not exists, ignore it and delete other resources continuely until try my best. This is almost `--force` by default.

Fixes #745

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Agreed @marun .  I'm not convinced that this PR is the right approach.

**Comment by xunpan** [comment]
My rules for message:
1.  each resource identity is print out with `%q`
2. `"namespace/resourcename"` is used in message.
3.  as output, I do not use resource name but use description. E.g. `ServiceAccount` is `service account`
4. `dry-run` will have no deleting message showed.
5. `errors.Wrap` are all in the lowest for kubernetes api calling.

**Comment by irfanurrehman** [comment]
@xunpan I think a flag to control the behaviour is still missing; the code will change considerably if you base the behaviour on user choice (similar to `error-on-existing` in `join`).

**Comment by xunpan** [comment]
@irfanurrehman Yes. I did not do it yet.
Did you share your thoughts for what is the case to use `exit-on-missing` like functions? I think a idempotent behavior is to `unjoin` cluster with deleting all existing resources. If it does not exists, it means it is deleted already. Just let it go. what is the reason to break it out?

**Comment by irfanurrehman** [comment]
1. So that the user can take informed decision. 
2. For useful debugging.
User might want to know which resource is/are missing while unjoin, in case they end up with half baked envs.
The default should ideally be unjoin with idempotency.
I am not too particular about this to be implemented necessarily as part of this PR. Idempotency in unjoin is more important as default behaviour, then having an option to choose it.

**Comment by marun** [comment]
@irfanurrehman In the `join` case, the user may not want an existing resource to be overwritten so `--error-on-existing` is a logical addition.  I don't think the same applies to `unjoin`, where no such possibility of negative user impact exists if a resource has already been deleted.  Yes, adding an equivalent flag has the potential to be useful for debugging.  That's not exactly the mission of `kubefedctl`, and insufficient justification for adding yet another knob for for user to consider.

**Comment by marun** [comment]
@xunpan Please rebase.  #876 removed all the previous cluster registry code.

File: pkg/kubefedctl/unjoin.go [hunk 1]
```diff
@@ -188,86 +189,88 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
-		klog.Errorf("Failed to delete Secret resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
+	if apierrors.IsNotFound(err) {
+		klog.V(2).Infof("Secret \"%s/%s\" does not exist in the host cluster.", federationNamespace, fedCluster.Spec.SecretRef.Name)
+	} else if err != nil {
+		message := fmt.Sprintf("Failed to delete secret \"%s/%s\" for unjoin cluster %q",
+			federationNamespace, fedCluster.Spec.SecretRef.Name, unjoiningClusterName)
+		if !forceDeletion {
+			return errors.Wrap(err, message)
+		}
+		klog.V(2).Infof("%s.", message)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: The wrapped error should be logged, not just the message.  Also, why is the period not included directly in the message?  Same comment on: 

 - [L248](https://github.com/kubernetes-sigs/federation-v2/pull/859/files#diff-66d64392a61d13d392f12c775c53b62fR248)
 - [L367](https://github.com/kubernetes-sigs/federation-v2/pull/859/files#diff-66d64392a61d13d392f12c775c53b62fR367)
 - [L385](https://github.com/kubernetes-sigs/federation-v2/pull/859/files#diff-66d64392a61d13d392f12c775c53b62fR385)
 - [L404](https://github.com/kubernetes-sigs/federation-v2/pull/859/files#diff-66d64392a61d13d392f12c775c53b62fR404)
 - [L422](https://github.com/kubernetes-sigs/federation-v2/pull/859/files#diff-66d64392a61d13d392f12c775c53b62fR422)

File: pkg/kubefedctl/unjoin.go [hunk 2]
```diff
@@ -188,86 +189,88 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, federationNamespace,
...
-		return
+		return errors.Wrapf(err, "Failed to get federated cluster \"%s/%s\"", federationNamespace, unjoiningClusterName)
 	}
 
 	err = hostClientset.CoreV1().Secrets(federationNamespace).Delete(fedCluster.Spec.SecretRef.Name,
 		&metav1.DeleteOptions{})
-	if err != nil {
-		klog.Errorf("Failed to delete Secret resource from namespace: %s for unjoin cluster: %s due to: %v", federationNamespace, unjoiningClusterName, err)
+	if apierrors.IsNotFound(err) {
+		klog.V(2).Infof("Secret \"%s/%s\" does not exist in the host cluster.", federationNamespace, fedCluster.Spec.SecretRef.Name)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: (No action required) Consider defining a `QualifiedName` instance instead of requiring `\"%s/%s\"` in all the messages.  Same comment wherever that awkward formatting is used repeatedly.

File: pkg/kubefedctl/unjoin.go (hunk 1 above)
Comment (xunpan) [reply pkg/kubefedctl/unjoin.go]: wrap uses `:` to seperate messages. So, extra `.` is not necessary. I remember related code in controller is already use such kind of convention though a little trivial.

Comment (marun) [reply pkg/kubefedctl/unjoin.go]: Apologies, I may have confused you.  If `forceDeletion == true`, `err` will not be logged at all.  I think the following would be preferable:

```golang
wrappedErr := errors.Wrapf(err, ...)
if !forceDeletion {
   return wrappedErr
}
klog.V(2).Infof("%v", wrappedErr)
```

Comment (xunpan) [reply pkg/kubefedctl/unjoin.go]: @marun done.

File: pkg/kubefedctl/unjoin.go (hunk 2 above)
Comment (xunpan) [reply pkg/kubefedctl/unjoin.go]: got it.

**Comment by marun** [comment]
Please rebase (the repo rename is complete).

File: pkg/kubefedctl/unjoin.go [hunk 3]
```diff
@@ -295,76 +303,132 @@ func deleteFedNSFromUnjoinCluster(hostClientset, unjoiningClusterClientset kubec
 		return nil
 	}
 
-	klog.V(2).Infof("Deleting kubefed namespace %q from unjoining cluster %q", kubefedNamespace, unjoiningClusterName)
+	klog.V(2).Infof("Deleting federation namespace %q from unjoining cluster %q.", kubefedNamespace, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: `s/federation/kubefed/`

File: pkg/kubefedctl/unjoin.go [hunk 4]
```diff
@@ -295,76 +303,132 @@ func deleteFedNSFromUnjoinCluster(hostClientset, unjoiningClusterClientset kubec
...
 	err = unjoiningClusterClientset.CoreV1().Namespaces().Delete(kubefedNamespace, &metav1.DeleteOptions{})
 	if apierrors.IsNotFound(err) {
-		klog.V(2).Infof("The kubefed namespace %q no longer exists in unjoining cluster %q", kubefedNamespace, unjoiningClusterName)
+		klog.V(2).Infof("The federation namespace %q no longer exists in unjoining cluster %q.", kubefedNamespace, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: `s/federation/kubefed/`

File: pkg/kubefedctl/unjoin.go [hunk 5]
```diff
@@ -295,76 +303,132 @@ func deleteFedNSFromUnjoinCluster(hostClientset, unjoiningClusterClientset kubec
...
 		return nil
+	} else if err != nil {
+		return errors.Wrapf(err, "Could not delete federation namespace %q from unjoining cluster %q", kubefedNamespace, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: `s/federation/kubefed/`

File: pkg/kubefedctl/unjoin.go [hunk 6]
```diff
@@ -188,86 +188,94 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, kubefedNamespace, hos
...
-	kubefedNamespace, unjoiningClusterName string, dryRun bool) {
+func deleteFederatedClusterAndSecret(hostClientset kubeclient.Interface, client genericclient.Client,
+	kubefedNamespace, unjoiningClusterName string, forceDeletion, dryRun bool) error {
 	if dryRun {
-		return
+		return nil
 	}
 
-	klog.V(2).Infof("Deleting federated cluster resource from namespace: %s for unjoin cluster: %s",
+	klog.V(2).Infof("Deleting federated cluster resource from namespace %q for unjoin cluster %q",
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: s/federated/kubefed/

File: pkg/kubefedctl/unjoin.go [hunk 7]
```diff
@@ -188,86 +188,94 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, kubefedNamespace, hos
...
 		kubefedNamespace, unjoiningClusterName)
 
 	fedCluster := &fedv1a1.KubefedCluster{}
 	err := client.Get(context.TODO(), fedCluster, kubefedNamespace, unjoiningClusterName)
 	if err != nil {
-		klog.Errorf("Failed to get KubefedCluster resource from namespace: %s for unjoin cluster: %s due to: %v", kubefedNamespace, unjoiningClusterName, err)
-		return
+		return errors.Wrapf(err, "Failed to get federated cluster \"%s/%s\"", kubefedNamespace, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: s/federated/kubefed/

File: pkg/kubefedctl/unjoin.go [hunk 8]
```diff
@@ -188,86 +188,94 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, kubefedNamespace, hos
...
 	} else {
-		klog.V(2).Infof("Deleted Secret resource from namespace: %s for unjoin cluster: %s", kubefedNamespace, unjoiningClusterName)
+		klog.V(2).Infof("Deleted secret \"%s/%s\" for unjoin cluster %q", kubefedNamespace, fedCluster.Spec.SecretRef.Name, unjoiningClusterName)
 	}
 
 	err = client.Delete(context.TODO(), fedCluster, fedCluster.Namespace, fedCluster.Name)
-	if err != nil {
-		klog.Errorf("Failed to delete KubefedCluster resource from namespace: %s for unjoin cluster: %s due to: %v", kubefedNamespace, unjoiningClusterName, err)
+	if apierrors.IsNotFound(err) {
+		klog.V(2).Infof("Federated cluster \"%s/%s\" does not exist in the host cluster.", fedCluster.Namespace, fedCluster.Name)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: s/Federated/KubeFed/

File: pkg/kubefedctl/unjoin.go [hunk 9]
```diff
@@ -188,86 +188,94 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, kubefedNamespace, hos
...
+	} else if err != nil {
+		wrappedErr := errors.Wrapf(err, "Failed to delete federated cluster \"%s/%s\" for unjoin cluster %q", fedCluster.Namespace, fedCluster.Name, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: s/federated/kubefed/

File: pkg/kubefedctl/unjoin.go [hunk 10]
```diff
@@ -188,86 +188,94 @@ func UnjoinCluster(hostConfig, clusterConfig *rest.Config, kubefedNamespace, hos
...
+		if !forceDeletion {
+			return wrappedErr
+		}
+		klog.V(2).Infof("%v", wrappedErr)
 	} else {
-		klog.V(2).Infof("Deleted KubefedCluster resource from namespace: %s for unjoin cluster: %s", kubefedNamespace, unjoiningClusterName)
+		klog.V(2).Infof("Deleted federated cluster \"%s/%s\" for unjoin cluster %q.", fedCluster.Namespace, fedCluster.Name, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: s/federated/kubefed/

File: pkg/kubefedctl/unjoin.go [hunk 11]
```diff
@@ -295,76 +303,132 @@ func deleteFedNSFromUnjoinCluster(hostClientset, unjoiningClusterClientset kubec
...
+	klog.V(2).Infof("Deleting federation namespace %q from unjoining cluster %q.", kubefedNamespace, unjoiningClusterName)
 	err = unjoiningClusterClientset.CoreV1().Namespaces().Delete(kubefedNamespace, &metav1.DeleteOptions{})
 	if apierrors.IsNotFound(err) {
-		klog.V(2).Infof("The kubefed namespace %q no longer exists in unjoining cluster %q", kubefedNamespace, unjoiningClusterName)
+		klog.V(2).Infof("The federation namespace %q no longer exists in unjoining cluster %q.", kubefedNamespace, unjoiningClusterName)
 		return nil
+	} else if err != nil {
+		return errors.Wrapf(err, "Could not delete federation namespace %q from unjoining cluster %q", kubefedNamespace, unjoiningClusterName)
+	} else {
+		klog.V(2).Infof("Deleted federation namespace %q from unjoining cluster %q.", kubefedNamespace, unjoiningClusterName)
```
Comment (marun) [inline pkg/kubefedctl/unjoin.go]: s/federation/kubefed/

**Comment by xunpan** [comment]
@marun done

**Comment by marun** [comment]
Thank you!  This was tricky to review (and presumably develop), so much repetition and the logic of the force deletion handling varied by function.  Hopefully we get a chance to cleanup at some point.

/approve
/lgtm
